/***** JOIN 실습 ****/

--1. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명 조회

-- ANSI
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
JOIN department ON(DEPT_CODE = DEPT_ID);

-- ORACLE
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--2. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명, 급여 조회;
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);

SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--3. EMPLOYEE 테이블과 SAL_GRADE 테이블을 조인해서
-- 각 직원의 이름과 급여 등급 조회
SELECT EMP_NAME, EMPLOYEE.SAL_LEVEL, MIN_SAL, MAX_SAL
FROM EMPLOYEE
JOIN SAL_GRADE ON (EMPLOYEE.SAL_LEVEL = SAL_GRADE.SAL_LEVEL);
/*
다른테이블에서 컬럼명은 다르지만 서로 의미하는 바가 같은 컬럼끼리는
컬럼명A = 컬럼명B 사용할 수 있음

다른 테이블에서 컬럼명이 같을 때는 참조하는 테이블이 무엇인지 작성해줘야함
테이블1명.컬럼명 = 테이블2명.컬럼명
*/
SELECT e.EMP_NAME, s.SAL_LEVEL, MIN_SAL, MAX_SAL
FROM EMPLOYEE e, SAL_GRADE s
WHERE e.SAL_LEVEL = s.SAL_LEVEL;

-- 각 직원의 이름과 그 직원이 속한 부서의 부서명 및 직급 조회
-- 테이블 EMPLOYEE, DEPARTMENT JOB

-- ANSI
SELECT EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE);
/*
E.DEPT_CODE = D.DEPT_ID
E.JOB_CODE = J.JOB_CODE

EMPLOYEE    DEPARTMENT  JOB
EMP_NAME    DEPT_TITLE  JOB_NAME
전지연	    인사관리부	대리
차태연	    인사관리부	대리
방명수	    인사관리부	사원
*/

-- ORACLE
SELECT EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE;

--1. 직원의 이메일 주소와 해당부서의 부서명 조회
-- TABLE : EMPLOYEE, DEPARTMENT
-- SELECT EMAIL DEPT_TITLE
SELECT E.EMAIL, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = d.dept_ID;

--2. 급여가 300만원 이상인 직원들의 이름과 그 직원이 속한 부서명 조회
-- TABLE : EMPLOYEE, DEPARTMENT
-- SELECT EMP_NAME, DEPT_TITLE
-- WHERE
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.dept_id AND E.SALARY >= 3000000;

--3. 각 직원의 이름과 그 직원이 속한 부서명의 부서명, 급여, 등급명 조회
-- TABLE : EMPLOYEE, DEPARTMENT, SAL_GRADE
-- SELECT : EMP_NAME, DEPT_TITLE, SAL_LEVEL
SELECT EMP_NAME, DEPT_TITLE, S.SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT D, SAL_GRADE S
WHERE E.dept_code = D.DEPT_ID AND E.sal_level = s.sal_level;

-- 4. 직급이 대리이면서 아시아 지역에 근무하는 직원 조회
-- 사번, 이름, 직급명, 부서명 근무지역명 급여 조회
-- TABLE EMPLOYEE, JOB, DEPARTMENT, LOCATION
SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.dept_code = D.DEPT_ID AND e.job_code = J.JOB_CODE AND d.location_id = L.LOCAL_CODE AND 
J.JOB_NAME = '대리'  AND SUBSTR(L.LOCAL_NAME, 1, 4) = 'ASIA';
-- L.LOCAL_NAME LIKE 'ASIA%'



-- 1. D5 부서에 속한 직원들의 이름과 직급명 조회
-- 테이블 EMPLOYEE, JOB
SELECT E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE AND E.DEPT_CODE = 'D5';

SELECT EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE = 'D5';

-- 2. 각 부서의 부서명과 해당 부서에 속한 직원의 평균급여 조회
-- 테이블 EMPLOYEE, DEPARTMENT
-- GROUP BY
-- AVG
SELECT DEPT_TITLE, ROUND(AVG(SALARY)) AS "평균급여"--, D.DEPT_ID
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID
GROUP BY D.DEPT_TITLE; --, D.DEPT_ID


--3. 급여 등급이 S4이상인 직원의 이름, 급여, 급여등급 조회
-- SELECT * FROM SAL_GRADE
-- 테이블 EMPLOYEE, SAL_GRADE
-- WHERE IN
SELECT E.EMP_NAME, E.SALARY, S.SAL_LEVEL
FROM EMPLOYEE E, SAL_GRADE S
WHERE E.SAL_LEVEL = S.SAL_LEVEL AND 
S.sal_level IN('S4', 'S5', 'S6');
